# Generated by Django 5.2.12 on 2026-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertapplication',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
