# Generated by Django 5.2.12 on 2026-04-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='任务标题')),
                ('category', models.CharField(choices=[('errand', '跑腿代购'), ('repair', '家电维修'), ('pet', '宠物照顾'), ('other', '其他互助')], default='other', max_length=20)),
                ('content', models.TextField(max_length=1000, verbose_name='任务详情')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='users.user')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tasks', to='users.user')),
            ],
        ),
    ]
