# Generated by Django 5.2.12 on 2026-04-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_task_abandon_reason_task_result_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=100, verbose_name='互助积分'),
        ),
    ]
