# Generated by Django 5.2.12 on 2026-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='audit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='审核评语'),
        ),
        migrations.AddField(
            model_name='task',
            name='intervention_decision',
            field=models.TextField(blank=True, null=True, verbose_name='仲裁理由'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='auditing', max_length=20),
        ),
    ]
