# Generated by Django 5.2.12 on 2026-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_task_audit_reason_task_intervention_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.IntegerField(default=10, verbose_name='悬赏积分'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='abandon_reason',
            field=models.TextField(blank=True, null=True, verbose_name='放弃/取消原因'),
        ),
        migrations.AlterField(
            model_name='task',
            name='audit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='管理员审核/拒绝理由'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='intervention_decision',
            field=models.TextField(blank=True, null=True, verbose_name='仲裁判定判定依据'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_desc',
            field=models.TextField(blank=True, null=True, verbose_name='达人提交成果描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='任务标题'),
        ),
    ]
