# Generated by Django 5.2.12 on 2026-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_communitytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('resident', '社区居民'), ('expert', '专业服务者(邻里达人)'), ('admin', '管理员')], default='resident', max_length=20, verbose_name='用户角色'),
        ),
    ]
