# Generated by Django 5.2.12 on 2026-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='community_zone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='社区片区'),
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
    ]
