# Generated by Django 5.2.12 on 2026-04-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_task_community_zone_task_latitude_task_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitytask',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='community_zone',
        ),
        migrations.RemoveField(
            model_name='task',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
