# Generated by Django 5.2.12 on 2026-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_communitytask_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
        migrations.AddField(
            model_name='task',
            name='reward_points',
            field=models.IntegerField(default=0, verbose_name='悬赏积分'),
        ),
    ]
